    <link rel="stylesheet" href="{{ asset('client/css/linearicons.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/font-awesome.min.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/themify-icons.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/bootstrap.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/owl.carousel.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/nice-select.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/nouislider.min.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/ion.rangeSlider.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/ion.rangeSlider.skinFlat.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/magnific-popup.css') }}">
	<link rel="stylesheet" href="{{ asset('client/css/main.css') }}">